# Generated by Django 3.1.4 on 2021-07-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0089_auto_20210713_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='higest_price_amount_hide',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lowest_price_amount_hide',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
