# Generated by Django 3.1.4 on 2021-07-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0090_auto_20210713_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='higest_price_amount_hide',
            new_name='highest_price_amount_hide',
        ),
    ]
